app/models.py
# models.py
import flask_login
from flask_login import UserMixin, current_user
import werkzeug
from sqlalchemy.ext.hybrid import hybrid_property
from flask_admin.contrib.sqla import ModelView
from flask_admin import AdminIndexView

from . import db
from .utils import ModelMixin

class User(UserMixin, db.Model): # SQL Table

    # Create attributes (SQL columns)
    id = db.Column(db.Integer, primary_key = True)
    username = db.Column(db.String(64))
    _password_hash    = db.Column(db.String(256))
    is_admin = db.Column(db.Boolean)
    reservation = db.relationship('Reservation', backref='user', lazy=True)

    @classmethod
    def login_user(cls, name, pwd):
        user = cls.query.filter_by(username=name).first()
        if user and user.check_password(pwd):
            flask_login.login_user(user)
            return user
        return False

    @hybrid_property
    def password(self):
        return self._password_hash

    @password.setter
    def password(self, pwd):
        self._password_hash = werkzeug.security.generate_password_hash(pwd)

    def check_password(self, pwd):
        return werkzeug.security.check_password_hash(self._password_hash, pwd)

    def __repr__(self):
        return f"<User {self.id}-{self.username}>"


class Hotel(db.Model):
    id = db.Column(db.Integer, primary_key = True)
    name = db.Column(db.String(64))
    location = db.Column(db.String(64))
    rooms_number = db.Column(db.Integer)
    reservation = db.relationship('Reservation', backref='hotel', lazy=True)
    price = db.Column(db.Integer)
    image1 = db.Column(db.String(256))
    image2 = db.Column(db.String(256))
    image3 = db.Column(db.String(256))
    image4 = db.Column(db.String(256))

class Reservation(db.Model):
    id = db.Column(db.Integer, primary_key = True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'),nullable=False)
    hotel_id = db.Column(db.Integer, db.ForeignKey('hotel.id'), nullable=False)
    start_date = db.Column(db.Date)
    end_date = db.Column(db.Date)

class  MyModelView(ModelView):
    def is_accessible(self):
        return current_user.is_authenticated and current_user.is_admin


  #  def inaccessible_callback(self, name, **kwargs):
        #redirect to login page if user doesn't have access
   #     return redirect(url_for('login', next=request.url))

class MyAdminIndexView(AdminIndexView):
    def is_accessible(self):
        return current_user.is_authenticated and current_user.is_admin
     

app/users/forms.py
#!/usr/bin/python3

##############################################
#
# app folder
# forms.py
#
##############################################
import flask_wtf
import wtforms
from flask_wtf import Form
from wtforms import validators as vld
from wtforms.fields.html5 import DateField

class SignupForm(flask_wtf.FlaskForm):

    username = wtforms.StringField("Name:", validators=[vld.DataRequired()])
    password = wtforms.PasswordField("Password:", validators=[vld.DataRequired()])

    submit   = wtforms.SubmitField("Sign up")

class SigninForm(flask_wtf.FlaskForm):

    username = wtforms.StringField("Name:", validators=[vld.DataRequired()])
    password = wtforms.PasswordField("Password:", validators=[vld.DataRequired()])

    submit   = wtforms.SubmitField("Sign in")

class ReserveForm(Form):
    start = DateField("Start Date: ", format = '%Y-%m-%d', validators=[vld.DataRequired()])
    end = DateField("End Date:  ", format = '%Y-%m-%d',validators=[vld.DataRequired()])

    submit = wtforms.SubmitField("Reserve")

app/__init__.py
# __init__.py
import flask
from config import config
import os

from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager
from flask_admin import Admin

db  = SQLAlchemy()
migrate = Migrate()
login_mgr = LoginManager()
admin = Admin(template_mode='bootstrap4')


def create_app():
    from .models import User, Hotel, Reservation
    from app.users.views import users

    env=os.environ.get("FLASK_ENV", "development")
    print("Using config", env)

    app = flask.Flask(__name__) # __name__ is the name of the folder
    app.config.from_object(config[env])

    app.register_blueprint(users)
   



    db.init_app(app)
    migrate.init_app(app, db)
    login_mgr.init_app(app)
    admin.init_app(app,index_view=models.MyAdminIndexView())



    @app.shell_context_processor
    def shell_ctx():
        return {
            "User": User,
            "app": app,
            "db": db,
            "auth": auth,
            "main":main
        }

    @login_mgr.user_loader
    def user_loader(user_id):
        return User.query.get(user_id)


    return app

app/users/__init__.py
# __init__.py
import flask
from app import db  # .. is previous folder
from app.utils import ModelMixin



users = flask.Blueprint("users", __name__)

from . import views
from app import models

app/users/views.py
#https://jamboard.google.com/d/1QkuB6jm7vekd6GwiLoENPpBq_kBgEfMF52uM8pK9Z4g/edit?usp=meet_whiteboard views.py
import flask, flask_login
from flask_login import current_user
from flask import session
from . import forms
from app import db, admin

from app.models import User, MyModelView, Hotel, Reservation
from app.users.forms import SigninForm, SignupForm

users = flask.Blueprint('users', __name__)

admin.add_view(MyModelView(User,db.session))
admin.add_view(MyModelView(Hotel,db.session))
admin.add_view(MyModelView(Reservation,db.session))


@users.route("/", methods=["GET", "POST"])
@users.route("/home", methods=["GET", "POST"])
def index():
    return flask.render_template("index.html", title="Dhotels")

@users.route("/sign-up", methods=["GET", "POST"])
def signup():
    form = forms.SignupForm()

    if flask.request.method == "POST":
        if form.validate_on_submit():

            user = User()
            user.username = form.username.data
            user.password = form.password.data

            db.session.add(user)
            db.session.commit()
         

            flask.flash("User has been successfully registered", category="success")

            return flask.redirect('/')
        else:
            print("Form errors:", form.errors)

    return flask.render_template("signup.html", form=form)


@users.route("/sign-in", methods=["GET", "POST"])
def signin():
    form = forms.SigninForm()
    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data
        user = User.login_user(username, password)
        if user:
            return flask.redirect('/')
        else:
            flask.flash("Bad credentials", category="error")

    return flask.render_template("signin.html", form=form)

@users.route("/sign-out")
def signout():
    flask_login.logout_user()
    flask.flash("Goodbye !", category="message")
    return flask.redirect('/')

@users.route("/locations")
def countries():
    hotel_locations = Hotel.query.all()

    return flask.render_template("countries.html",title ='Hotel Locations',hotel_locations = hotel_locations)

@users.route("/reservations/<user_id>")
def reservations(user_id):
    

    reservations_list = Reservation.query\
        .join(Hotel, Reservation.hotel_id == Hotel.id)\
        .filter(Reservation.user_id == user_id).all()
    print([ r.hotel.name for r in reservations_list])
    if not reservations_list:
        flask.flash("No reservations found", category="error")
        return flask.redirect('/')
    


    return flask.render_template("reservations.html",title ='Your Reservations',user_reservations = reservations_list)

@users.route("/reserve/<hotel_id>",methods=["GET", "POST"])
def reserve(hotel_id):
    form = forms.ReserveForm()
    print(current_user)
    if flask.request.method == "POST":
        if form.validate_on_submit():

            reservation = Reservation()
            reservation.start_date = form.start.data
            reservation.end_date = form.end.data
            reservation.hotel_id = hotel_id
            reservation.user_id = current_user.id
            

            db.session.add(reservation)
            db.session.commit()
         

            flask.flash("Your reservation has been successfully registered", category="success")

            return flask.redirect('/')
        else:
            print("Form errors:", form.errors)

    hotel = Hotel.query.filter_by(id=hotel_id).first()
    return flask.render_template("reserve.html", title='Reserve',hotel=hotel,form=form)

app/templates/base.html
<html>

<header>
     <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <title>{{ title }}</title>
    <link rel="stylesheet" href="/static/master.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
</header>

<body>
    {% block navbar %}
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <a class="navbar-brand" href="/">DHotels</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
              <a class="nav-item nav-link active" href="{{ url_for('users.index') }}">Home <span class="sr-only">(current)</span></a>
              <a class="nav-item nav-link" href="{{ url_for('users.countries') }}">Locations</a>
              {% if current_user.is_authenticated %}
                  <a class="nav-item nav-link disabled"> Welcome {{ current_user.username }} !</a>
                  <a class="nav-item nav-link " href="{{ url_for('users.reservations' , user_id=current_user.id)}}">Your Reservations</a>
                  <a class="nav-item nav-link " href="{{ url_for('users.signout') }}">sign out</a>
                
              {% else %}
              <a class="nav-item nav-link" href="{{ url_for('users.signin') }}">Sign in</a>
              <a class="nav-item nav-link" href="{{ url_for('users.signup') }}">Sign up</a>

              {% endif %}
            </div>
          </div>
        </nav>
    {% endblock %}

    <div class="container">
        {% for category, msg in get_flashed_messages(with_categories=True) %}
            {% if category == "error" %}
            <div class="alert alert-danger" role="alert">
                {{ msg }}
            </div>
            {% endif %}
            {% if category == "success" %}
            <div class="alert alert-success" role="alert">
                {{ msg }}
            </div>
            {% endif %}
            {% if category == "message" %}
            <div class="alert alert-secondary" role="alert">
                {{ msg }}
            </div>
            {% endif %}
        {% endfor %}

        {% block main %}
        {% endblock %}

    </div>

    <div class="container">
        <footer class="blockquote-footer">
            DHotels
        </footer>
    </div>
</body>

</html>

app/templates/countries.html
{% extends "base.html" %}

{% block main %}
    <h1> Locations </h1>
    {% for hotel in hotel_locations %}
    <br><br>
    {% set current_id = hotel['id'] %}
<div>
    <h2> {{hotel['name'] }} </h2>
<div class="row">
<div class="col-sm-6">
    <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
          <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
          <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
          <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
          <li data-target="#carouselExampleCaptions" data-slide-to="3"></li>
        </ol>
        <div class="carousel-inner">
          <div class="carousel-item active">
            <img src="{{hotel['image1'] }}" class="d-block w-100" alt="...">
            <div class="carousel-caption d-none d-md-block">
              
            </div>
          </div>
          <div class="carousel-item">
            <img src="{{hotel['image2'] }}" class="d-block w-100" alt="...">
            <div class="carousel-caption d-none d-md-block">
              <h5>Loby</h5>
            </div>
          </div>
          <div class="carousel-item">
            <img src="{{hotel['image3'] }}" class="d-block w-100" alt="...">
            <div class="carousel-caption d-none d-md-block">
             
            </div>
          </div>
          <div class="carousel-item" id>
            <img src="{{hotel['image4'] }}" class="d-block w-100" alt="...">
            <div class="carousel-caption d-none d-md-block">
                <h5>Room</h5>
            </div>
          </div>
        </div>
      </div>
    </div>

<div class="col-sm-2">
</div>
<div class="col-sm-4">
    <br><br>
    <div style="text-align: center">
    <img src="https://icon-library.com/images/star-rating-icon/star-rating-icon-21.jpg" width="{{ 300 }}" height="{{ 70 }}"/>
    <br><br>
    <h3>Price for night:</h3>
    <h4 style="color:green">{{hotel['price'] }}$</h4>
    <br>

    <a type="button" class="btn btn-secondary btn-lg" href="{{ url_for('users.reserve', hotel_id=current_id)}}" >Reserve Now</a>
</div>
</div>
</div>
    {% endfor %}
{% endblock %}

app/templates/index.html
{% extends "base.html" %}

{% block main %}
    <br><p ></p>
        <h1>Welcome to DHotels!</h1><br>
        <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">
              <div class="carousel-item active">
                <img class="d-block w-100" src="https://images.unsplash.com/photo-1583037189850-1921ae7c6c22?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=668&q=80" alt="First slide">
              </div>
              <div class="carousel-item">
                <img class="d-block w-100" src="https://images.unsplash.com/photo-1560200353-ce0a76b1d438?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=667&q=80" alt="Second slide">
              </div>
              <div class="carousel-item">
                <img class="d-block w-100" src="https://images.unsplash.com/photo-1566073771259-6a8506099945?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=750&q=80" alt="Third slide">
              </div>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="sr-only">Next</span>
            </a>
          </div>
        

{% endblock %}

app/templates/reservations.html
{% extends "base.html" %}

{% block main %}
    <h1> Your Reservations</h1>
 
    <br><br>
    <table class="table">
        <thead class="thead-light">
          <tr>
            <th scope="col">Reservation</th>
            <th scope="col">Hotel</th>
            <th scope="col">Start Date</th>
            <th scope="col">End Date</th>
            <th scope="col">Price</th>
          </tr>
        </thead>
        <tbody>
      
        {% for reservation in user_reservations %}
          {% set days = reservation.end_date - reservation.start_date %}
          {% set price_ = days.days * reservation.hotel.price %}
          <tr>
            <th scope="row">{{ loop.index }}</th>
            <td>{{reservation.hotel.name}}</td>
            <td>{{reservation['start_date'] }}</td>
            <td>{{reservation['end_date'] }}</td>
            <td>{{price_}}$</td>
          </tr>
         
          {% endfor %}
        </tbody>
      </table>



    
{% endblock %}

app/templates/reserve.html
{% extends "base.html" %}

{% block main %}
{% set msg = 'Sign in first!' %}
{% if current_user.is_authenticated %}
    <h1>Welcome to {{hotel['name']}}</h1>
    <form action="" novalidate method="post">
        {{form.csrt_token}}
        {{ form.hidden_tag() }}
        <div> 
            {{ form.start.label }}
            {{ form.start(class="datepicker") }}

            {% for error in form.start.errors %}
                <small>{{ error }}</small>
            {% endfor %}
        </div>

        <div>
            {{ form.end.label }}
            {{ form.end(class="datepicker") }}

            {% for error in form.end.errors %}
                <small>{{ error }}</small>
            {% endfor %}
        </div>
       

        {{ form.submit(class="form-control") }}
    </form>
{% else %}

<div class="alert alert-danger" role="alert">
    {{ msg }}
</div>


{% endif %}
    
{% endblock %}

app/templates/signin.html
{% extends "base.html" %}

{% block main %}

    <form action="" novalidate method="post">

        {{ form.hidden_tag() }}

        <div>
            {{ form.username.label }}
            {{ form.username(class="form-control") }}

            {% for error in form.username.errors %}
                <small>{{ error }}</small>
            {% endfor %}
        </div>

        <div>
            {{ form.password.label }}
            {{ form.password(class="form-control") }}

            {% for error in form.password.errors %}
                <small>{{ error }}</small>
            {% endfor %}
        </div>

        {{ form.submit(class="form-control") }}
    </form>


{% endblock %}

app/templates/signup.html
{% extends "base.html" %}

{% block main %}

    <form action="" novalidate method="post">

        {{ form.hidden_tag() }}

        <div>
            {{ form.username.label }}
            {{ form.username(class="form-control") }}

            {% for error in form.username.errors %}
                <small>{{ error }}</small>
            {% endfor %}
        </div>

        <div>
            {{ form.password.label }}
            {{ form.password(class="form-control") }}

            {% for error in form.password.errors %}
                <small>{{ error }}</small>
            {% endfor %}
        </div>

        {{ form.submit(class="form-control") }}
    </form>


{% endblock %}

app/templates/users_list.html
{% extends "base.html" %}
{% block main %}
    <h1>Users:</h1>

    {% for user in users %}
    <div>
        <p>Name: {{ user.name }}</p>
    </div>
    {% endfor %}
{% endblock %}